config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home/home'
  root to: 'home#home'

  devise_for :users
  resources :words
  resources :lessons, only: %i[show index new create]
  resources :lessons_words, only: %i[new create]
  resources :tests, only: %i[new create show]
  resources :groups
  resources :profile, except: %(new create index)
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  has_many :user_groups, dependent: nil
  has_many :users, through: :user_groups
  has_many :lessons, dependent: :destroy
  validates :title, presence: true
end

app/models/lesson.rb
# frozen_string_literal: true

class Lesson < ApplicationRecord
  has_many :lessons_words, dependent: :destroy
  has_many :words, through: :lessons_words
  has_many :tests, dependent: :destroy
  has_many :users, through: :tests
  belongs_to :group
  validates :title, presence: true
end

app/models/lessons_word.rb
# frozen_string_literal: true

class LessonsWord < ApplicationRecord
  belongs_to :lesson
  belongs_to :word
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :lesson
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_groups, dependent: nil
  has_many :groups, through: :user_groups
  has_many :tests, dependent: :destroy
  has_many :lessons, through: :test

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true

  enum role: { student: 0, teacher: 1 }
end

app/models/user_group.rb
# frozen_string_literal: true

class UserGroup < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/word.rb
# frozen_string_literal: true

class Word < ApplicationRecord
  has_many :lessons_words, dependent: :destroy
  has_many :lessons, through: :lessons_words
  validates :word, :description, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:first_name, :last_name, :email, :password)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:first_name, :last_name, :email, :password)
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_group, only: %i[show edit update destroy]

  def index
    @groups = Group.all
  end

  def show; end

  def create
    @group = Group.new(group_params)

    if @group.save
      format.html { redirect_to @group, notice: 'Group was successfully created.' }
    else
      format.html { render action: 'new' }
    end
  end

  def new
    @group = Group.new
  end

  def edit; end

  def update
    if @group.update(group_params)
      format.html { redirect_to @group, notice: 'Group was successfully updated.' }
    else
      format.html { render action: 'edit' }
    end
  end

  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  private

  def group_params
    params.require(:group).permit(:title)
  end

  def find_group
    @group = Group.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home; end
end

app/controllers/lessons_controller.rb
# frozen_string_literal: true

class LessonsController < ApplicationController
  # before_action :authenticate_user!

  def index
    @lessons = Lesson.all
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @group  = Group.find(params.dig(:lesson, :group_id))
    @lesson = @group.lessons.create(lesson_params)
    if @lesson.save
      render status: :created
    else
      render status: :unprocessable_entity, json: @lesson.errors.full_messages
    end
  end

  def show
    @lesson = Lesson.find(params[:id])
  end

  private

  def lesson_params
    params.require(:lesson).permit(:title, :group_id)
  end
end

app/controllers/lessons_words_controller.rb
# frozen_string_literal: true

class LessonsWordsController < ApplicationController
  def new
    @lessons_word = LessonsWord.new
  end

  def create
    @lessons_word = LessonsWord.create(lessons_words_params)
    if @lessons_word.save
      render status: :created
    else
      render status: :unprocessable_entity, json: @lessons_word.errors.full_messages
    end
  end

  private

  def lessons_words_params
    params.require(:lessons_word).permit(:word_id, :lesson_id)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user

  def edit; end

  def update
    if @user.update(user_params)
      format.html { redirect_to @user, notice: 'User was successfully updated.' }
    else
      format.html { render action: 'edit' }
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to user_url }
      format.json { head :no_content }
    end
  end

  def show; end

  private

  def find_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :authenticate_user!

  def new
    @lesson = Lesson.find_by(id: params[:lesson_id])
  end

  def create
    user_translations = params[:user_translations]

    @test = Test.create(lesson_id: params[:lesson_id], user: current_user,
                        user_translations: user_translations,
                        mark: TestService.new(lesson, user_translations).calculate_mark)

    if @test.save
      redirect_to @test, user_translations: params[:user_translations]
    else
      render 'new'
    end
  end

  def show
    @test = Test.find(params[:id])
  end

  def lesson
    @lesson ||= Lesson.find_by(id: params[:lesson_id])
  end
end

app/controllers/words_controller.rb
# frozen_string_literal: true

class WordsController < ApplicationController
  def index
    @words = Word.all
  end

  def show
    @word = Word.find(params[:id])
  end

  def new
    @word = Word.new
  end

  def create
    @word = Word.create(word_params)
    if @word.save
      render status: :created
    else
      render status: :unprocessable_entity, json: word.errors.full_messages
    end
  end

  def edit
    @word = Word.find(params[:id])
  end

  def update
    @word = Word.find(params[:id])
    if @word.update(word_params)
      redirect_to word_path(@word)
    else
      render status: :unprocessable_entity, json: @word.errors.full_messages
    end
  end

  def destroy
    @word = Word.find(params[:id])
    @word.destroy

    redirect_to words_path
  end

  private

  def word_params
    params.require(:word).permit(:word, :description, :translation, :lesson_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/groups/edit.html.erb
<h3>Update Group Details</h3>
<%= form_with model: @group do |form| %>
  <%= form.text_field :title, placeholder: "title" %>
  <%= form.submit %>
<% end %>

app/views/groups/index.html.erb
<ul>
  <% @groups.each do |group| %>
    <li><%= link_to group.name, group_path(group)  %></li> # title?
  <% end %>
</ul>

<table>
  <% @groups.each do |group| %>
    <tr>
      <td><%= link_to group.name, group_path(group) %></td> # title?
      <td><%= button_to 'Edit', edit_group_path(group), method: 'get'%></td>
      <td><%= button_to 'Remove', group_path(group), method: 'delete', data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>
<%= link_to "Add a New Group", new_group_path %>

app/views/groups/new.html.erb
<h3>Create a Group</h3>
<%= form_with model: @group do |form| %>
  <%= form.text_field :title, placeholder: "title" %>
  <%= form.submit %>
<% end %>

app/views/groups/show.html.erb
<%= link_to 'Remove', @group, method: :delete, data: { confirm: 'Are you sure?' } %>
<h1><%= @group.title %></h1>

app/views/home/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Standard Meta -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">


  <style type ="text/css">

      .hidden.menu {
          display: none;
      }

      .masthead.segment {
          min-height: 700px;
          padding: 1em 0em;
      }
      .masthead .logo.item img {
          margin-right: 1em;
      }
      .masthead .ui.menu .ui.button {
          margin-left: 0.5em;
      }
      .masthead h1.ui.header {
          margin-top: 3em;
          margin-bottom: 0em;
          font-size: 4em;
          font-weight: normal;
      }
      .masthead h2 {
          font-size: 1.7em;
          font-weight: normal;
      }

      .ui.vertical.stripe {
          padding: 8em 0em;
      }
      .ui.vertical.stripe h3 {
          font-size: 2em;
      }
      .ui.vertical.stripe .button + h3,
      .ui.vertical.stripe p + h3 {
          margin-top: 3em;
      }
      .ui.vertical.stripe .floated.image {
          clear: both;
      }
      .ui.vertical.stripe p {
          font-size: 1.33em;
      }
      .ui.vertical.stripe .horizontal.divider {
          margin: 3em 0em;
      }

      .quote.stripe.segment {
          padding: 0em;
      }
      .quote.stripe.segment .grid .column {
          padding-top: 5em;
          padding-bottom: 5em;
      }

      .footer.segment {
          padding: 5em 0em;
      }

      .secondary.pointing.menu .toc.item {
          display: none;
      }

      @media only screen and (max-width: 700px) {
          .ui.fixed.menu {
              display: none !important;
          }
          .secondary.pointing.menu .item,
          .secondary.pointing.menu .menu {
              display: none;
          }
          .secondary.pointing.menu .toc.item {
              display: block;
          }
          .masthead.segment {
              min-height: 350px;
          }
          .masthead h1.ui.header {
              font-size: 2em;
              margin-top: 1.5em;
          }
          .masthead h2 {
              margin-top: 0.5em;
              font-size: 1.5em;
          }
      }


  </style>

  <script src="assets/library/jquery.min.js"></script>
  <script src="../dist/components/visibility.js"></script>
  <script src="../dist/components/sidebar.js"></script>
  <script src="../dist/components/transition.js"></script>
  <script>
      $(document)
          .ready(function() {

              // fix menu when passed
              $('.masthead')
                  .visibility({
                      once: false,
                      onBottomPassed: function() {
                          $('.fixed.menu').transition('fade in');
                      },
                      onBottomPassedReverse: function() {
                          $('.fixed.menu').transition('fade out');
                      }
                  })
              ;

              // create sidebar and attach to menu open
              $('.ui.sidebar')
                  .sidebar('attach events', '.toc.item')
              ;

          })
      ;
  </script>
</head>
<body>

<!-- Following Menu -->
<div class="ui large top fixed hidden menu">
<!--  <div class="ui container">-->
<!--    <a class="active item">Home</a>-->
<!--    <a class="item">Work</a>-->
<!--    <a class="item">Company</a>-->
<!--    <a class="item">Careers</a>-->
    <div class="right menu">
      <div class="item">
        <a class="ui button">Log in</a>
      </div>
      <div class="item">
        <a class="ui primary button">Sign Up</a>
      </div>
    </div>
<!--  </div>-->
</div>

<!-- Sidebar Menu -->
<div class="ui vertical inverted sidebar menu">
<!--  <a class="active item">Home</a>-->
<!--  <a class="item">Work</a>-->
<!--  <a class="item">Company</a>-->
<!--  <a class="item">Careers</a>-->
  <a class="item">Login</a>
  <a class="item">Signup</a>
</div>


<!-- Page Contents -->
<div class="pusher">
  <div class="ui inverted vertical masthead center aligned segment">

    <div class="ui container">
      <div class="ui large secondary inverted pointing menu">
        <a class="toc item">
          <i class="sidebar icon"></i>
        </a>
<!--        <a class="active item">Home</a>-->
<!--        <a class="item">Work</a>-->
<!--        <a class="item">Company</a>-->
<!--        <a class="item">Careers</a>-->
        <div class="right item">
        <% if user_signed_in?  %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"ui inverted button" %>
        <% else %>  
        <%= link_to "Log in", new_user_session_path, class:"ui inverted button" %>
        <%= link_to "Sign in", new_user_registration_path, class:"ui inverted button" %>
        <% end %>  
        </div>
      </div>
    </div>

    <div class="ui text container">
      <h1 class="ui inverted header">
        English for IT
      </h1>
      <h2>Learn IT smart! ;)</h2>
      <div class="ui huge primary button">Get Started <i class="right arrow icon"></i></div>
    </div>

  </div>

  <div class="ui vertical stripe segment">
    <div class="ui middle aligned stackable grid container">
      <div class="row">
        <div class="eight wide column">
          <h3 class="ui header">What's this app for?</h3>
          <p>Hi, Everybody! Welcome to our application for developers! We know that it is really important to know English in IT.
          Every developer should know this language for reading documentation, working with code and understanding programs.
          With English you will be able to read the best of the resources from Internet. And we also know, than learning Englsh
          can be difficult. Our App can help you to learn and remember Eng. words easy & fast. So... What are you waiting for? Try it out !</p>
<!--          <h3 class="ui header">We Make Bananas That Can Dance</h3>-->
<!--          <p>Yes that's right, you thought it was the stuff of dreams, but even bananas can be bioengineered.</p>-->
        </div>
        <div class="six wide right floated column">
          <img src="learn-new-language/app/views/home/city-buildings-skyline-metropolitan-area_31965-7268.jpg" class="ui large bordered rounded image" alt="Picture with city">
        </div>
      </div>
<!--      <div class="row">-->
<!--        <div class="center aligned column">-->
<!--          <a class="ui huge button">Check Them Out</a>-->
<!--        </div>-->
      </div>
    </div>
  </div>

  <div class="ui inverted vertical footer segment">
    <div class="ui container">
      <div class="ui stackable inverted divided equal height stackable grid">
        <div class="three wide column">
          <h4 class="ui inverted header">Authors</h4>
          <div class="ui inverted link list">
            <a href="#" class="item">Valeria Radchenko</a>
            <a href="#" class="item">Denys Davydov</a>
            <a href="#" class="item">Maria Voitovych</a>
            <a href="#" class="item">Weremite</a>
          </div>
        </div>
        <div class="three wide column">
          <h4 class="ui inverted header">Mentors</h4>
          <div class="ui inverted link list">
            <a href="#" class="item">Viktor</a>
            <a href="#" class="item">Pavlo Kasianchuk</a>
<!--            <a href="#" class="item">How To Access</a>-->
<!--            <a href="#" class="item">Favorite X-Men</a>-->
          </div>
        </div>
<!--        <div class="seven wide column">-->
<!--          <h4 class="ui inverted header">Footer Header</h4>-->
<!--          <p>Extra space for a call to action inside the footer that could help re-engage users.</p>-->
<!--        </div>-->
      </div>
    </div>
  </div>
</div>

</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Language</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css" rel="stylesheet">
    <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <title>Homepage - Semantic</title>
    <link rel="stylesheet" type="text/css" href="../dist/components/reset.css">
    <link rel="stylesheet" type="text/css" href="../dist/components/site.css">

    <link rel="stylesheet" type="text/css" href="../dist/components/container.css">
    <link rel="stylesheet" type="text/css" href="../dist/components/grid.css">
    <link rel="stylesheet" type="text/css" href="../dist/components/header.css">
    <link rel="stylesheet" type="text/css" href="../dist/components/image.css">
    <link rel="stylesheet" type="text/css" href="../dist/components/menu.css">

    <link rel="stylesheet" type="text/css" href="../dist/components/divider.css">
    <link rel="stylesheet" type="text/css" href="../dist/components/dropdown.css">
    <link rel="stylesheet" type="text/css" href="../dist/components/segment.css">
    <link rel="stylesheet" type="text/css" href="../dist/components/button.css">
    <link rel="stylesheet" type="text/css" href="../dist/components/list.css">
    <link rel="stylesheet" type="text/css" href="../dist/components/icon.css">
    <link rel="stylesheet" type="text/css" href="../dist/components/sidebar.css">
    <link rel="stylesheet" type="text/css" href="../dist/components/transition.css">
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>


  </body>
</html>

app/views/lessons/create.html.erb
Lesson: <%= @lesson.title %>

<small>
| <%= @lesson.created_at&.strftime('%D')  %>
</small>

app/views/lessons/index.html.erb
<div class="lesson-main"> 
  <h1 class="lesson-header"> Your last lessons: </h1>

  <div class="ui grid container">
    <% @lessons.each do |lesson|%>
      <div class="four wide column">
        <div class="lesson-example">
          <div class="lesson-column-content">
            <%= image_tag "pexels-fauxels-3183132.jpg", height: 150 %> <br>
            <%= lesson.id %>. <%= link_to lesson.title, lesson_path(lesson), class: "white-label" %>
          </div> 
        </div>  
      </div>
    <% end %> 
  </div>
</div>

app/views/lessons/new.html.erb
<div id = "lesson">
  <h3>Create a lesson</h3>
  <%= form_with model: @lesson do |form| %>
    <%= form.text_field :title, placeholder: "title" %>
    <%= form.text_field :group_id, placeholder: "group_id" %>

    <%= form.submit %>
  <% end %>
</div>

app/views/lessons/show.html.erb
<div class="lesson-main"> 
  <h1 class="lesson-header"> Lesson <%= @lesson.id %>. <%= @lesson.title %> </h1>


<h2> Lessons words: </h2>

<ul id = 'index word'>
  <% @lesson.words.each do |word|%>
    <li><%= link_to word.word, word_path(word)  %></li> 
  <% end %> 
</ul>

<h2> PASS TEST: </h2>

<div>
  <% @lesson.tests.each do |test|%>
    <%= link_to "Pass #{test.id} test", new_test_path(lesson_id: @lesson.id), class: "btn ui secondary button" %> 
  <% end %> 
</div>
</div>

 

app/views/lessons_words/create.html.erb
Word with id: <%= @lessons_word.word_id %>
added to lesson with id: <%= @lessons_word.lesson_id %>

app/views/lessons_words/new.html.erb
<div id = 'lessons_word'>
  <h3>Add word to lesson</h3>
  <%= form_with model: @lessons_word do |form| %>
    <%= form.text_field :word_id, placeholder: "word_id" %>
    <%= form.text_field :lesson_id, placeholder: "lesson_id" %>
    <%= form.submit %>
  <% end %>
</div>

app/views/profiles/edit.html.erb
<h3>Edit Profile</h3>

<%= form_with(model: @user, url: profile_path) do |form| %>
  <%= form.text_field :email, placeholder: "email" %>
  <%= form.text_field :first_name, placeholder: "first_name" %>
  <%= form.submit %>
<% end %>

app/views/profiles/show.html.erb
<%= link_to 'Remove', @user, method: :delete, data: { confirm: 'Are you sure?' } %>
<h1><%= @user.title %></h1>

app/views/words/create.html.erb
Word: <%= @word.word %>

Description: <%= @word.description %>

<small>
| <%= @word.created_at&.strftime('%D')  %>
</small>

app/views/words/edit.html.erb
<h3>Update Word</h3>
<%= form_with model: @word do |form| %>
  <%= form.text_field :word, placeholder: "word" %>
  <%= form.text_field :description, placeholder: "description" %>
  <%= form.submit %>
<% end %>

app/views/words/index.html.erb
<ul id = 'index word'>
  <% @words.each do |word| %>
    <li><%= link_to word.word, word_path(word)  %></li>
  <% end %>
</ul>

app/views/words/new.html.erb
<div id = 'create_word'>
  <h3>Create a word</h3>
  <%= form_with model: @word do |form| %>
    <%= form.text_field :word, placeholder: "word" %>
    <%= form.text_field :description, placeholder: "description" %>
    <%= form.submit %>
  <% end %>
</div>

app/views/words/show.html.erb
<%= link_to 'Remove', @word, method: :delete, data: { confirm: 'Are you sure?' } %>